openapi: 3.1.0
info:
  version: 0.2.0
  title: ECHE List API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: api.support@uni-foundation.eu
    url: 'https://github.com/EuropeanUniversityFoundation/eche-api'
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://uni-foundation.eu/wp-content/uploads/2019/04/EUF-1.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Institutions
    description: See all _Institutions_ in the ECHE list, with optional filtering.
servers:
  - url: 'https://eche-list.erasmuswithoutpaper.eu/api'
    description: Production server
  - url: '/api'
    description: Current server
paths:
  /:
    $ref: paths/list.yaml
  /{key}/{value}:
    $ref: paths/filter.yaml
  /{key}:
    $ref: paths/null.yaml
