# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1:
    root: openapi/openapi.yaml
rules:
  no-unused-components: error
theme:
  openapi:
    showConsole: true
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#32329f"
