openapi: 3.1.0
info:
  version: 0.1.0
  title: ECHE API
  termsOfService: https://example.com/terms/
  contact:
    email: api.support@uni-foundation.eu
    url: https://github.com/EuropeanUniversityFoundation/eche-api
  x-logo:
    url: https://uni-foundation.eu/wp-content/uploads/2019/04/EUF-1.png
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.


    # Introduction


    _tbd_
tags:
  - name: List
    description: Exposes the complete ECHE list.
servers:
  - url: /api/v0.1
    description: Sandbox server (example data)
paths:
  /list:
    get:
      tags:
        - List
      summary: GET /
      description: |
        This endpoint lists all _Institutions_ covered by this provider.
      operationId: getList
      responses:
        '200':
          description: OK
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user.
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstitutionCollection'
              example:
                - proposalNumber: '111111111'
                  erasmusCode: AQ TESTING99
                  pic: '999999999'
                  oid: E11111111
                  organisationLegalName: TEST ENTRY
                  street: Main street 1
                  postalCode: null
                  city: Ridley Beach
                  country: Antarctica
                  webpage: https://example.com
                  echeStartDate: '2021-01-01'
                  echeEndDate: '2029-12-31'
        '400':
          $ref: '#/components/responses/Problem'
components:
  schemas:
    InstitutionCollection:
      type: array
      description: List of _Institution_ resources.
      items:
        type: object
        required:
          - proposalNumber
          - erasmusCode
          - pic
          - organisationLegalName
          - street
          - city
          - country
          - echeStartDate
          - echeEndDate
        properties:
          proposalNumber:
            type: string
            description: Proposal Number
          erasmusCode:
            type: string
            description: Erasmus Code
          pic:
            type: string
            description: PIC
          oid:
            type: string
            description: OID
          organisationLegalName:
            type: string
            description: Organisation Legal Name
          street:
            type: string
            description: Street
          postalCode:
            type: string
            description: Postal Code
          city:
            type: string
            description: City
          country:
            type: string
            description: Country
          webpage:
            type: string
            description: Webpage
          echeStartDate:
            type: string
            description: ECHE Start Date
          echeEndDate:
            type: string
            description: ECHE End Date
    Problem:
      type: object
      additionalProperties: true
      minProperties: 1
      description: >-
        The Problem Details JSON Object
        [[RFC7807](https://tools.ietf.org/html/rfc7807)].
      properties:
        type:
          type: string
          description: >-
            A URI reference [[RFC3986](https://tools.ietf.org/html/rfc3986)]
            that identifies the problem type. It should provide human-readable
            documentation for the problem type. When this member is not present,
            its value is assumed to be "about:blank".
          format: uri
        title:
          type: string
          description: >-
            A short, human-readable summary of the problem type. It SHOULD NOT
            change from occurrence to occurrence of the problem, except for
            purposes of localization.
        status:
          type: integer
          description: The HTTP status code.
          minimum: 400
          maximum: 599
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
        instance:
          type: string
          description: >-
            A URI reference that identifies the specific occurrence of the
            problem.  It may or may not yield further information if
            dereferenced.
  responses:
    Problem:
      description: Problem
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
